### ISSUE TITLE
Failed to include an async function

### ISSUE THREAD

**Issue by rafaesc92** [jsdoc2md/jsdoc-api#10]
Hello,
When I add an async function, the explainSync method fails, this is the case

```
var jsdocApi = require("jsdoc-api");

console.log(jsdocApi.explainSync({ source: `
/** example doclet */
var example = true

async function onSubmit () {
    console.log('example')
}
` }))
```

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
Appreciate your help. Thanks.

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2016-features
