### ISSUE TITLE
JSDOC_ERROR: ERROR: Unable to parse file ...

### ISSUE THREAD

**Issue by taburetkin** [jsdoc2md/jsdoc-api#18]
## environment:
win10
jsdoc3
node 10.15.3

## project setup
```
E:\_dev\_jsstack\own-casino\routing:
  jsdoc2md.js
  config.js
```  

### jsdoc2md.js:
```js
const jsdoc = require('jsdoc-api');

let res = jsdoc.explainSync({
  files: ['./config.js'],
  source: {
    excludePattern: null
  }
});
console.log(res);
```
# the Problem
as i found out few days ago when tested jsdocs CLI, they have default excludePattern  
`"excludePattern": "(^|\\/|\\\\)_"`  
This prevent to process any file if there is an underscore in the path (say folder name starts with underscore)
the default jsdoc cli returns an error: `JSDOC_ERROR: There are no input files to process`
so, i have to use CLI with custom config where i can setup this excludePattern and in that case everything is working good.

Same thing happens when i tried jsdoc-api.
In first place i got exception "There are no input files to process"
then i tried redefine default excludePattern and now i am getting this error:
```
E:\_dev\_jsstack\own-casino\routing\node_modules\jsdoc-api\lib\jsdoc-command.js:114
      throw err
      ^

JSDOC_ERROR: ERROR: Unable to parse C:\Users\dim\AppData\Local\Temp\nzib7okrirep26r717gm9.js: Unexpected token, expected "," (1:8)
```
what you can suggest me?

with best regards

**Comment by 75lb** [comment]
the `source` option takes a string, not an object as you are passing.. 
https://github.com/jsdoc2md/jsdoc-api#module_jsdoc-api..JsdocOptions+source

**Comment by taburetkin** [comment]
Oh, i see... i was wrong thinking that `source` is like jsdoc source.
i should use options.configure : string
The path to the configuration file. Default: path/to/jsdoc/conf.json.

sorry for bothering.
