### ISSUE TITLE
'undocumented' parameter

### ISSUE THREAD

**Issue by djKooks** [jsdoc2md/jsdoc-api#20]
I'm checking the result from parsing javascript file with `explainSync`, and seems `undocumented` parameter means whether this has been documented or not:
```
[
...
  },
  {
    ...
    name: "docName",
    undocumented: true,
    kind: "function",
  }
{
...
]
```
But when there are documents information, this `undocumented` key are not exists, instead of showing `undocumented: false`.

Would it be better to set this value when document exists?

Thanks.

**Comment by 75lb** [comment]
Hi, I'm sorry - I can't help you with this issue. The output of jsdoc-api is the direct output of jsdoc. Jsdoc-api is a wrapper for jsdoc, nothing more. If you have an issue with the jsdoc output, please raise it with https://github.com/jsdoc/jsdoc.

**Comment by djKooks** [comment]
@75lb thanks for comment~
