### ISSUE TITLE
.files or .source options should be optional if .configure is set

### ISSUE THREAD

**Issue by cowwoc** [jsdoc2md/jsdoc-api#27]
Currently, if one passes in the path to a configuration file via the `configure` option we still get this error message:

`Must set either .files or .source options`

If the configuration file already specifies one of these, it shouldn't be mandatory to repeat them.

**Comment by cowwoc** [comment]
Is the code even making use of `configure` anywhere? I can see the code accepting it as a parameter but it doesn't look like it ever gets used. This is increasingly looking like a bug to me.

**Comment by 75lb** [comment]
Fixed and released in [v9.0.0](https://github.com/jsdoc2md/jsdoc-api/releases/tag/v9.0.0) - let me know if you find anything else 👍 . 

Yes, the configure file is honoured if passed in. The implemented rule is that you must now pass one of `files`, `source` or `configure`.
