### ISSUE TITLE
child process on close event fires too early in jsdoc-api/lib/explain.js:Explain#_runJsdoc

### ISSUE THREAD

**Issue by Manu-san** [jsdoc2md/jsdoc-api#4]
Hello,
in my project i'm using "jsdoc-parse" to analyze some JSDoc at runtime. 
To process the data, i'am using the parser in stream-pipe with some manipulation transform and finally collect it as object data with "stream-collect" to return a promise:
```javascript
    return jsdocParse({
      'src': [
        jsdocCommonArgumentsPath,
        jsdocArgumentsPath
      ],
      'stats': false,
      'html': false
    })
      .pipe(JSONStream.parse('*'))
      .pipe(new ReduceJSDocArgumentsObjectStreamTransform)
      .pipe(collect.objectStream())
      .then(function mergeResult(res) {
        return _.concat.apply(this, res);
      });
```
That works just fine as long it's working at all. But i've found out, that in jsdoc-api/lib/explain.js the method _runJSdoc has a problem. In this method the stdout and stderr -streams are collected and after spawn a "node"-child-process with jsdoc-75lb and params, the collected data is processed on handle.on('close'). But this is fired sometimes too early and the stdout data is not collected yet. In such a case the stdout is empty and the "verifyOutput"-method fails at parsing the empty content with JSON.parse.

My tested working suggestion is as following:

```javascript
  _runJsdoc() {
    let _this = this;

    return new Promise((resolve, reject) => {
      const collectAll = require('collect-all');

      // Important! Not listen only to handle.on('close')-event, stdout.on('end') can fire after it 
      // and thus it's possible that stdout-data is not fully collected yet.
      let isStderrEnd = false;
      let isStdoutEnd = false;
      let isProcessClose = false;
      let processCloseCode = 0;

      function finished() {
        if (isStderrEnd && isStdoutEnd && isProcessClose) {
          setTimeout(() => {
            try {
              const explainOutput = _this.verifyOutput(processCloseCode, jsdocOutput);
              if (_this.options.cache) {
                _this.cache.write(_this.cacheKey, explainOutput).then(() => resolve(explainOutput))
              } else {
                resolve(explainOutput)
              }
            } catch (err) {
              reject(err)
            }
          });
        }
      }

      const jsdocOutput = {
        'stdout': '',
        'stderr': '',
        collectInto (dest) {
          return collectAll(data => {
            this[dest] = data.toString();
          })
        }
      };

      const toSpawnArgs = require('object-to-spawn-args');
      const jsdocArgs = toSpawnArgs(_this.jsdocOptions).concat(['-X'])
        .concat(_this.options.source ? _this.tempFile.path : _this.inputFileSet.files);
      jsdocArgs.unshift(_this.jsdocPath);

      const spawn = require('child_process').spawn;
      const handle = spawn('node', jsdocArgs);

      handle.stderr.on('end', () => {
        isStderrEnd = true;
        finished();
      });
      handle.stdout.on('end', () => {
        isStdoutEnd = true;
        finished();
      });
      handle.on('close', (code) => {
        processCloseCode = code;
        isProcessClose = true;
        finished();
      });
      handle.stderr.pipe(jsdocOutput.collectInto('stderr'));
      handle.stdout.pipe(jsdocOutput.collectInto('stdout'));
    })
  }
```

I'm using nodejs v4.5.0 on Windows x64.

Best regards,
Manusan

**Comment by 75lb** [comment]
Hi, thanks for the report - i will look at this today. To be honest, i am
considering removing the stream interface from jsdoc-api as it adds no
additional benefit over the Promise interface.

**Comment by 75lb** [comment]
Is there any particular reason you used the stream interface over `.explain
()`?

**Comment by Manu-san** [comment]
Like i've posted above, i'am using jsdoc-parse to parse the docs from code files and jsdoc-parse returns a stream. With a stream-transform i'm manipulating the output.

Which alternative interface do you mean?

**Comment by 75lb** [comment]
take a look at the [.getTemplateData() method](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/next/docs/API.md) on the jsdoc2md [prerelease](https://github.com/jsdoc2md/jsdoc-to-markdown/releases).. this method returns the jsdoc-parse data.. the stream interfaces have been removed from the next versions of the modules.. you code should look something like 

```js
const jsdoc2md = require('jsdoc-to-markdown')

const options = {
  files: [
    jsdocCommonArgumentsPath,
    jsdocArgumentsPath
  ]
}

jsdoc2md.getTemplateData(options)
  .then(data => {
    // process output
  })
```

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-api/releases.

Thanks for the report.

**Comment by Manu-san** [comment]
I'am writing production code for my company, I cannot use some alpha version of a module, so would you mind fixing _runJsdoc() and publish a v1.2.8 tag für jsdoc-parse that i can stay with streaming interface which i've implemented already?

**Comment by 75lb** [comment]
i'm no longer maintaining the stream interface.. i recommend you fork jsdoc-api and use the solution you posted above until you're comfortable moving to jsdoc2md v2. 

Sorry for the inconvenience.

**Comment by Manu-san** [comment]
ok, i'll do so, thx
