### ISSUE TITLE
JSDOC_ERROR when running README example

### ISSUE THREAD

**Issue by donaldpipowitch** [jsdoc2md/jsdoc-api#5]
When I run `jsdoc.explainSync({ source: '/** example doclet *∕ \n var example = true' })` from the README, I get this error:

```
     JSDOC_ERROR: ERROR: Unable to parse /var/folders/g1/kj7f1k4973l0fd3c2mjnf9j80000gp/T/7pdqccagq0n51cn39ozmxfajorl4by2ka8czrrqa8n8uygmn29.js: Line 2: Unexpected token ILLEGAL
      at ExplainSync.verifyOutput (node_modules/jsdoc-api/lib/jsdoc-command.js:114:19)
```

**Comment by 75lb** [comment]
looking into, thanks

**Comment by 75lb** [comment]
sorry, it was because the README example contained a unicode forward-slash, instead of the regular ASCII one.. try this instead: 
```
jsdoc.explainSync({ source: '/** example doclet */ \n var example = true' })
```

Thanks for letting me know!

**Comment by donaldpipowitch** [comment]
Cool, thanks for the fast fix!
