### ISSUE TITLE
Path of temporary file contains underscore, no files to process

### ISSUE THREAD

**Issue by pstadler** [jsdoc2md/jsdoc-api#6]
We're running into an issue where we randomly get "There are no input files to process" errors.

Initially files run through https://github.com/jsdoc2md/gulp-jsdoc-to-markdown. At some point the following command is executed: `jsdoc -X /var/folders/dx/_yc89prs1fq_g81m07nqjjy00000gn/T/t5v3v4ty2pvjblis4mbdibe2920pl85ipt5rz0afwkpy76cg14i.js`.

This fails, because jsdoc's file parser contains an `excludePattern` matching underscores at the beginning of files and seemingly also folders.

There are at least three options how to solve this:
1) Pass a config file to jsdoc using `-c`, see here: https://github.com/jsdoc3/jsdoc/issues/1155
2) Make sure the temporary path doesn't contain leading underscores
3) Fix jsdoc itself to only match leading underscores at the beginning of files, but not folders

Let me know if I can be of any help here.

**Comment by 75lb** [comment]
jeez, what an inconvenient rule for jsdoc to have!

1. This might be my only option (to override the built-in jsdoc `excludePattern`).
2. It's the system tempdir, I have no control
3. Pfft, I'm not posting any more issues or PRs to jsdoc. Maintenance is minimal.

Can you workaround the issue temporarily by passing a custom `excludePattern` to [options.configure](https://github.com/jsdoc2md/jsdoc-api#optionsconfigure--string)?

**Comment by 75lb** [comment]
Also, gulp-jsdoc-to-markdown is deprecated and uses an old version of jsdoc-api internally - I don't intend to patch the old version. The latest jsdoc-api only uses temporary files if `source: true` was passed. Could you confirm whether using the [current recommended gulp method](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-gulp) fixes your issue?

**Comment by 75lb** [comment]
closing until more feedback received.

**Comment by pstadler** [comment]
Hi there. Thanks for the fast response.

I was able to get rid of the gulp plugin. In case somebody struggles with the same problem, here's an example:

```js
// gulp task
gulp.src(files)
  .pipe(through.obj(function (file, enc, done) {
    jsdoc2md.render({
      source: file.contents.toString(),
      template: template,
      'no-cache': true,
      configure: __dirname + '/jsdoc-config.json'
    }).then(function (result) {
      file.contents = new Buffer(result);

      done(null, file);
    }).catch(done);
  }));

// jsdoc-config.json
{
  "source": {
    "excludePattern": ""
  }
}

```
